apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-pre-upgrade-hook"
  annotations:
    "helm.sh/hook": "pre-upgrade"
    "helm.sh/hook-delete-policy": "hook-failed"
spec:
  template:
    spec:
      containers:
        - name: pre-upgrade-job
          image: hub.17ker.top/library/busybox:latest 
          command:
            - sh
            - -c
            - |
              echo "Helm Hook | pre-upgrade | {{ .Release.Name }} | {{ .Values.hookMessages.preUpgrade }}"
      restartPolicy: Never

